/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      "colors": {
        "inverse-on-surface": "#283044",
        "outline-variant": "#3e484f",
        "on-primary": "#00354a",
        "surface": "#0b1326",
        "tertiary-container": "#30c88f",
        "on-tertiary": "#003824",
        "tertiary": "#56e5a9",
        "surface-variant": "#2d3449",
        "surface-container-lowest": "#060e20",
        "secondary": "#bdc2ff",
        "surface-container": "#171f33",
        "on-secondary": "#131e8c",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#bdc2ff",
        "background": "#0b1326",
        "on-secondary-fixed-variant": "#2f3aa3",
        "primary-container": "#38bdf8",
        "primary": "#8ed5ff",
        "secondary-container": "#2f3aa3",
        "on-primary-fixed": "#001e2c",
        "on-secondary-fixed": "#000767",
        "tertiary-fixed": "#6ffbbe",
        "surface-tint": "#7bd0ff",
        "on-background": "#dae2fd",
        "outline": "#87929a",
        "on-tertiary-fixed": "#002113",
        "on-surface-variant": "#bdc8d1",
        "surface-container-highest": "#2d3449",
        "on-error": "#690005",
        "primary-fixed-dim": "#7bd0ff",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface-dim": "#0b1326",
        "on-primary-container": "#004965",
        "error-container": "#93000a",
        "on-secondary-container": "#a8afff",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#e0e0ff",
        "primary-fixed": "#c4e7ff",
        "on-tertiary-container": "#004e34",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#dae2fd",
        "on-primary-fixed-variant": "#004c69",
        "surface-bright": "#31394d",
        "inverse-surface": "#dae2fd",
        "inverse-primary": "#00668a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "xs": "0.5rem",
        "md": "1.5rem",
        "sm": "1rem",
        "margin": "2rem",
        "xl": "4rem",
        "unit": "4px",
        "gutter": "1.5rem",
        "lg": "2.5rem"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Space Grotesk"],
        "headline-xl": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-lg": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "code-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}

